export const genres = [
  {
    id: "27",
    kind: "genre",
    russian: "Сёнен",
    entryType: "Anime",
    name: "Shounen",
  },
  {
    id: "28",
    kind: "genre",
    russian: "Сёнен-ай",
    entryType: "Anime",
    name: "Shounen Ai",
  },
  {
    id: "42",
    kind: "genre",
    russian: "Сэйнэн",
    entryType: "Anime",
    name: "Seinen",
  },
  {
    id: "25",
    kind: "genre",
    russian: "Сёдзё",
    entryType: "Anime",
    name: "Shoujo",
  },
  {
    id: "26",
    kind: "genre",
    russian: "Сёдзё-ай",
    entryType: "Anime",
    name: "Shoujo Ai",
  },
  {
    id: "43",
    kind: "genre",
    russian: "Дзёсей",
    entryType: "Anime",
    name: "Josei",
  },
  {
    id: "4",
    kind: "genre",
    russian: "Комедия",
    entryType: "Anime",
    name: "Comedy",
  },
  {
    id: "22",
    kind: "genre",
    russian: "Романтика",
    entryType: "Anime",
    name: "Romance",
  },
  {
    id: "23",
    kind: "genre",
    russian: "Школа",
    entryType: "Anime",
    name: "School",
  },
  {
    id: "13",
    kind: "genre",
    russian: "Исторический",
    entryType: "Anime",
    name: "Historical",
  },
  {
    id: "16",
    kind: "genre",
    russian: "Магия",
    entryType: "Anime",
    name: "Magic",
  },
  {
    id: "18",
    kind: "genre",
    russian: "Меха",
    entryType: "Anime",
    name: "Mecha",
  },
  {
    id: "20",
    kind: "genre",
    russian: "Пародия",
    entryType: "Anime",
    name: "Parody",
  },
  {
    id: "21",
    kind: "genre",
    russian: "Самураи",
    entryType: "Anime",
    name: "Samurai",
  },
  {
    id: "32",
    kind: "genre",
    russian: "Вампиры",
    entryType: "Anime",
    name: "Vampire",
  },
  {
    id: "35",
    kind: "genre",
    russian: "Гарем",
    entryType: "Anime",
    name: "Harem",
  },
  {
    id: "36",
    kind: "genre",
    russian: "Повседневность",
    entryType: "Anime",
    name: "Slice of Life",
  },
  {
    id: "37",
    kind: "genre",
    russian: "Сверхъестественное",
    entryType: "Anime",
    name: "Supernatural",
  },
  {
    id: "17",
    kind: "genre",
    russian: "Боевые искусства",
    entryType: "Anime",
    name: "Martial Arts",
  },
  {
    id: "11",
    kind: "genre",
    russian: "Игры",
    entryType: "Anime",
    name: "Game",
  },
  {
    id: "40",
    kind: "genre",
    russian: "Психологическое",
    entryType: "Anime",
    name: "Psychological",
  },
  {
    id: "19",
    kind: "genre",
    russian: "Музыка",
    entryType: "Anime",
    name: "Music",
  },
  {
    id: "1",
    kind: "genre",
    russian: "Экшен",
    entryType: "Anime",
    name: "Action",
  },
  {
    id: "6",
    kind: "genre",
    russian: "Демоны",
    entryType: "Anime",
    name: "Demons",
  },
  {
    id: "39",
    kind: "genre",
    russian: "Полиция",
    entryType: "Anime",
    name: "Police",
  },
  {
    id: "9",

    kind: "genre",
    russian: "Этти",
    entryType: "Anime",
    name: "Ecchi",
  },
  {
    id: "10",
    kind: "genre",
    russian: "Фэнтези",
    entryType: "Anime",
    name: "Fantasy",
  },
  {
    id: "543",
    kind: "genre",
    russian: "Гурман",
    entryType: "Anime",
    name: "Gourmet",
  },
  {
    id: "29",
    kind: "genre",
    russian: "Космос",
    entryType: "Anime",
    name: "Space",
  },
  {
    id: "541",
    kind: "genre",
    russian: "Работа",
    entryType: "Anime",
    name: "Work Life",
  },
  {
    id: "14",
    kind: "genre",
    russian: "Ужасы",
    entryType: "Anime",
    name: "Horror",
  },
  {
    id: "2",
    kind: "genre",
    russian: "Приключения",
    entryType: "Anime",
    name: "Adventure",
  },
  {
    id: "24",
    kind: "genre",
    russian: "Фантастика",
    entryType: "Anime",
    name: "Sci-Fi",
  },
  {
    id: "31",
    kind: "genre",
    russian: "Супер сила",
    entryType: "Anime",
    name: "Super Power",
  },
  {
    id: "38",
    kind: "genre",
    russian: "Военное",
    entryType: "Anime",
    name: "Military",
  },
  {
    id: "7",
    kind: "genre",
    russian: "Детектив",
    entryType: "Anime",
    name: "Mystery",
  },
  {
    id: "15",
    kind: "genre",
    russian: "Детское",
    entryType: "Anime",
    name: "Kids",
  },
  {
    id: "3",
    kind: "genre",
    russian: "Машины",
    entryType: "Anime",
    name: "Cars",
  },
  {
    id: "8",
    kind: "genre",
    russian: "Драма",
    entryType: "Anime",
    name: "Drama",
  },
  {
    id: "5",
    kind: "genre",
    russian: "Безумие",
    entryType: "Anime",
    name: "Dementia",
  },
  {
    id: "30",
    kind: "genre",
    russian: "Спорт",
    entryType: "Anime",
    name: "Sports",
  },
  {
    id: "41",
    kind: "genre",
    russian: "Триллер",
    entryType: "Anime",
    name: "Thriller",
  },
  {
    id: "539",
    kind: "genre",
    russian: "Эротика",
    entryType: "Anime",
    name: "Erotica",
  },
  {
    id: "12",
    kind: "genre",
    russian: "Хентай",
    entryType: "Anime",
    name: "Hentai",
  },
  {
    id: "33",
    kind: "genre",
    russian: "Яой",
    entryType: "Anime",
    name: "Yaoi",
  },
  {
    id: "34",
    kind: "genre",
    russian: "Юри",
    entryType: "Anime",
    name: "Yuri",
  },
];
